NordicSemiconductor/npmx-zephyr

drivers/npmx/npmx_shell.c
JIRA: NRFX-3903
DNM until:
* https://github.com/NordicSemiconductor/npmx-zephyr/pull/18
=> drivers: npmx: npmx_shell: add reset command

drivers/npmx/npmx_shell.c
JIRA: NRFX-3850
DNM until:
* https://github.com/NordicSemiconductor/npmx-zephyr/pull/18
=> drivers: npmx: npmx_shell: add buck mode setter command

drivers/npmx/npmx_shell.c
=> drivers: add buck status power get command to shell

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add charger warm termination voltage commands

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: NTC module control based on ntc type

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add timer configuration commands

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add LED mode and state commands

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add POF configuration commands

west.yml
Without connected NTC the temperature is -88.11*C 
`uart:~$ [00:00:01.436,828] <inf> fuel_gauge: V: 4.184, I: 0.000, T: -88.11, SoC: 98.88, TTE: nan, TTF: nan`
=> manifest: update npmx to have better natural logarithm implementation

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add LDSW active-discharge enable commands

drivers/npmx/npmx_driver.c, dts/bindings/mfd/nordic,npmx-npm1300.yaml
=> drivers: npmx: make interrupt pins optional

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: fix for ldsw soft start enable argument checking

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add gpio status get command

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add LDSW GPIO enable commands

drivers/npmx/npmx_shell.c
Recalculation of NTC resistance after beta changes for temperatures set beforehand. Change of NTC type does not affect the code value written to the register (equation from Figure 23 from IPS v 0.53).
Die temperatures do not depend on NTC type or beta value.
Recalculation is done by reading the old resistance value, calculating it to the temperature value, and then recalculating resistance for that temperature. Although it requires additional computing, it does not increase the execution time of a command in a noticeable way.
test:PR-177
=> Nrfx 4720 recalculate temperature when ntc changed

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: fix gpio index for config

west.yml
=> manifest: sdk-nrfxlib: update to v2.5.0-rc1

drivers/npmx/npmx_shell.c
=> drivers: npmx: shell: add ntc temp range checking in set commands

drivers/npmx/npmx_shell.c
Added timer start, stop, load_config and watchdog kick commands.
=> drivers: npmx: shell: add new timer commands

samples/timer/src/main.c, samples/timer_wakeup/src/main.c, samples/timer_watchdog/src/main.c, west.yml
=> Nrfx 4806 move timer strobe fix from shell to npmx

drivers/npmx/shell/buck.c, drivers/npmx/shell/ldsw.c
=> LDSW & BUCK: split GPIO cmds

drivers/npmx/shell/buck.c, drivers/npmx/shell/shell_common.c, drivers/npmx/shell/shell_common.h, west.yml
~~Based on https://github.com/NordicSemiconductor/npmx-zephyr/pull/117~~ Rebased on develop
Please, review only the last commit.
=> Nrfx 4851 replace checking gpio instance number

drivers/npmx/shell/charger.c, drivers/npmx/shell/shell_common.c, drivers/npmx/shell/shell_common.h
=> drivers: npmx: shell: add helper functions for rounding setters

Jenkinsfile, doc/conf.py, doc/release_notes.rst, samples/fuel_gauge/src/fuel_gauge.c, west.yml
Updated fuel gauge samples for latest algorithm version from nrfxlib.
Includes cc_charging parameter to improve accuracy of TTF calculations.
=> samples: fuel_gauge: Updated to latest nrfxlib
